// Afprøver Genveje.html mappedialogen i en simuleret browser (jsdom). Kør med: npm test
const fs=require("fs");const {JSDOM}=require("jsdom");
let fails=0;const ok=(c,m)=>{console.log((c?"  ✔ ":"  ✘ ")+m);if(!c)fails++};
function load(storage={}){return new JSDOM(fs.readFileSync(require("path").join(__dirname, "..", "Genveje.html"),"utf8"),{url:"http://localhost/",runScripts:"dangerously",beforeParse(w){for(const[k,v]of Object.entries(storage))w.localStorage.setItem(k,v);w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){if(!this.open)return;this.open=false;this.dispatchEvent(new w.Event("close"))};w.matchMedia=()=>({matches:false});w.confirm=()=>true}}).window}
const files=w=>["Rapporter/Budget 2026.xlsx","Rapporter/~$Budget 2026.xlsx","Rapporter/WEEE/Q1 #2.pdf","Rapporter/WEEE/Arkiv/gammel.docx","Rapporter/desktop.ini"].map(p=>{const f=new w.File(["x"],p.split("/").pop());Object.defineProperty(f,"webkitRelativePath",{value:p});return f});
const pickFolder=w=>{const i=w.document.getElementById("fdInput");Object.defineProperty(i,"files",{value:files(w),configurable:true});i.dispatchEvent(new w.Event("change"))};
const $=(w,s)=>w.document.querySelector(s),$$=(w,s)=>[...w.document.querySelectorAll(s)];
console.log("Mappe-dialog, første gang");
let w=load();
$(w,"#addFilesBtn").click();
ok($(w,"#fdStep2").hidden,"trin 2 skjult før mappevalg");
pickFolder(w);
ok(!$(w,"#fdStep2").hidden,"trin 2 vises efter mappevalg");
ok($(w,"#fdPath").value===""&&$(w,"#fdPathHint").textContent.startsWith("Første gang"),"sti tom + vejledning første gang");
const names=$$(w,"#fdList .frow .name").map(e=>e.textContent);
ok(names.join("|")==="Rapporter|WEEE|Arkiv|Budget 2026.xlsx|gammel.docx|Q1 #2.pdf","liste: mappe, undermapper, filer uden lås/systemfiler: "+names.join("|"));
$(w,"#fdPath").value="C:\\Users\\Michael\\Andet";$(w,"#fdPath").dispatchEvent(new w.Event("input"));
ok(!$(w,"#fdWarn").hidden,"advarsel når stien ikke passer til mappen");
$(w,"#fdPath").value="\"C:\\Users\\Michael\\Rapporter\"";$(w,"#fdPath").dispatchEvent(new w.Event("input"));
ok($(w,"#fdWarn").hidden,"ingen advarsel når navnet passer (anførselstegn tåles)");
$(w,"#fdType").value="files";$(w,"#fdType").dispatchEvent(new w.Event("change"));
$(w,"#fdAll").click();
ok(/\(3\)/.test($(w,"#fdAdd").textContent),"vælg alle viste filer: "+$(w,"#fdAdd").textContent);
const ti=$(w,"#fdTagsBox input");ti.value="rapport";ti.dispatchEvent(new w.KeyboardEvent("keydown",{key:"Enter",bubbles:true}));
$(w,"#fform").dispatchEvent(new w.Event("submit",{cancelable:true}));
let st=JSON.parse(w.localStorage.getItem("genveje.state"));
const added=st.links.filter(l=>l.url.startsWith("file:"));
ok(added.length===3,"3 filer tilføjet");
ok(added.some(l=>l.url==="file:///C:/Users/Michael/Rapporter/WEEE/Q1%20%232.pdf"),"sti med # og mellemrum kodet korrekt");
ok(added.every(l=>l.tags&&l.tags[0]==="rapport"),"tags til alle sat");
ok(JSON.parse(w.localStorage.getItem("genveje.folders")).rapporter==="C:\\Users\\Michael\\Rapporter","stien huskes");
console.log("Mappe-dialog, anden gang");
$(w,"#addFilesBtn").click();pickFolder(w);
ok($(w,"#fdPath").value==="C:\\Users\\Michael\\Rapporter"&&$(w,"#fdPathHint").textContent.startsWith("Husket"),"sti udfyldt automatisk");
ok($$(w,"#fdList .frow.exists").length===3,"de 3 tilføjede filer er markeret 'findes allerede'");
const dirBox=$$(w,"#fdList input").find(c=>c.dataset.key==="d:WEEE");dirBox.checked=true;dirBox.dispatchEvent(new w.Event("change",{bubbles:true}));
$(w,"#fform").dispatchEvent(new w.Event("submit",{cancelable:true}));
st=JSON.parse(w.localStorage.getItem("genveje.state"));
ok(st.links.some(l=>l.url==="file:///C:/Users/Michael/Rapporter/WEEE/"&&l.icon==="📂"),"mappelink tilføjet med / til sidst");
const row=$$(w,"#grid .row").find(r=>r.textContent.includes("Q1 #2"));
ok(row&&row.querySelector(".sub").textContent==="C:\\Users\\Michael\\Rapporter\\WEEE\\Q1 #2.pdf","stien vises læsbart: "+(row&&row.querySelector(".sub").textContent));
console.log(fails?fails+" FEJL":"Alle test bestået");
process.exit(fails?1:0);
